services:
  - type: web
    name: fem_connect
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: DJANGO_SETTINGS_MODULE=core.settings.staging gunicorn core.wsgi:application

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.staging
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: false
      - key: ENVIRONMENT
        value: staging
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
